version: "3.8"

x-api-config: &api-config
  env_file: accessmap-incremental.env
  build:
    context: ./accessmap-api

x-router-config: &router-config
  env_file: accessmap-incremental.env
  build: ./dockerfiles/unweaver

services:
  caddy:
    env_file: accessmap-incremental.env
    image: abiosoft/caddy:0.11.5-no-stats
    restart: unless-stopped
    volumes:
      - ./config/caddy/Caddyfile:/etc/Caddyfile
      - caddy-persist:/root/.caddy
      - ./output/transportation-tasks.geojson:/data/transportation.geojson
    ports:
      - 2015:2015
    links:
      - router
      - api

  api:
    <<: *api-config
    command: poetry run gunicorn --bind 0.0.0.0:5000 'wsgi:build_app(endpoint="/api/v1")'
    stop_signal: SIGINT
    restart: unless-stopped
    ports:
      - 5000:5000
    dns:
      - 8.8.8.8
      - 8.8.4.4

  router:
    <<: *router-config
    command: poetry run unweaver serve /data -h 0.0.0.0 -p 5656
    restart: unless-stopped
    stop_signal: SIGINT
    ports:
      - 5656:5656
    volumes:
      - ./build/router:/data:rw

  build_router:
    <<: *router-config
    command: bash -c "cp -r /inputconfig/* /data && cp -r /inputdata/layers /data/ && poetry run unweaver build /data --changes-sign incline"
    # Makes progress bar update in the terminal
    tty: true
    volumes:
      - ./config/unweaver:/inputconfig:rw
      - ./output/transportation-tasks.geojson:/inputdata/layers/transportation.geojson:ro
      - ./build/router:/data:rw
    profiles:
      - build

volumes:
  caddy-persist:
